# Generated by Django 4.2.16 on 2024-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ringtone',
            name='rate_avg',
        ),
        migrations.RemoveField(
            model_name='ringtone',
            name='total_download',
        ),
        migrations.RemoveField(
            model_name='ringtone',
            name='total_rate',
        ),
        migrations.RemoveField(
            model_name='ringtone',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='ringtone',
            name='user',
        ),
        migrations.AddField(
            model_name='ringtone',
            name='ringtone_year',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
