# Generated by Django 4.2.16 on 2024-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0006_alter_ringtone_play_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ringtone',
            old_name='ringtone_year',
            new_name='ringtone_year_end',
        ),
        migrations.AddField(
            model_name='ringtone',
            name='ringtone_year_start',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
