# Generated by Django 4.2.16 on 2024-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0008_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringtone_language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ringtone_language_images/'),
        ),
    ]
